Add call for community reviewers.
djangocon/2024-old.djangocon.us pull request #36
Opened 2024-04-07 14:01 UTC by tim-schilling

This is based on the 2019 post:
https://github.com/djangocon/2019.djangocon.us/blob/main/_posts/2019-05-02-call-for-community-reviewers.md

<img width="692" alt="Screen Shot 2024-04-07 at 8 57 43 AM" src="https://github.com/djangocon/2024.djangocon.us/assets/1281215/dc618341-febb-4957-9d8f-71435358c544">

2024-04-07 14:22 UTC, drewbrew approved these changes

2024-04-07 15:31 UTC, jefftriplett requested changes

2024-04-07 15:31 UTC, jefftriplett commented on _posts/2024-04-08-call-for-community-reviewers.md
> +post_photo_alt: "Lacey Williams Henschel speaking at DjangoCon US 2018"
FYI, Lacey shortened her name to remove the Williams. See https://github.com/williln and her blog for the context change. 

```suggestion
post_photo_alt: "Lacey Henschel speaking at DjangoCon US 2018"
```

2024-04-07 16:31 UTC, tim-schilling commented on _posts/2024-04-08-call-for-community-reviewers.md
> +post_photo_alt: "Lacey Williams Henschel speaking at DjangoCon US 2018"
Thank you for catching that

2024-04-08 01:56 UTC, jefftriplett approved these changes
Looks good!

2024-04-08 14:21 UTC, merged